[package]
name = "qbice_storage"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
qbice_serialize = { version = "0.1.0", path = "../serialize" }
qbice_stable_type_id = { version = "0.1.0", path = "../stable_type_id" }
tokio.workspace = true
parking_lot.workspace = true
fxhash.workspace = true
futures.workspace = true

[lints]
workspace = true
