[package]
name = "qbice_stable_hash"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
siphasher.workspace = true
static_assertions.workspace = true
dashmap.workspace = true
flexstr.workspace = true
qbice_stable_hash_derive = { path = "../stable_hash_derive" }

[lints]
workspace = true
